name: Deploy Page

on:
  push:
    branches:
      - main

jobs:
  docs:
    uses: pmndrs/docs/.github/workflows/build.yml@v2
    with:
      mdx: "docs"
      base_path: ""
      libname: "Immersive React"
      icon: "🥽"
      home_redirect: "/introduction-to-react-three-fiber/0-getting-started"
      libname_dotsuffix_label: ""

  assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: public/

  bundle-artifacts:
    runs-on: ubuntu-latest
    needs:
      - assets
      - docs
    steps:
      - name: Download Examples Artifiact
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: ./out

      - name: Download Docs Artifiact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./

      - name: Extract Docs
        run: tar -xf ./artifact.tar -C ./out/

      - name: Create deploy.tar
        working-directory: ./out
        run: tar -cf deploy.tar ./*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: ./out/deploy.tar

  deploy:
    needs:
      - bundle-artifacts
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: deploy
